### ISSUE TITLE
Feature: support for HTTP/S proxy

### ISSUE THREAD

**Issue by jhochman** [Y2Z/monolith#103]
Would be great if it supported HTTP_PROXY/HTTPS_PROXY environment variable to make it work with a proxy server. Thanks!

**Comment by snshn** [comment]
Hi Josh,

thank you for reporting this!

Judging from https://github.com/seanmonstar/reqwest/blob/master/tests/proxy.rs#L20 it could be as little as a couple lines of code to implement this

**Comment by rhysd** [comment]
I have experience to support HTTP proxies with reqwest library. Let me have a try.

**Comment by rhysd** [comment]
I have created PR for this: https://github.com/Y2Z/monolith/pull/106
