### ISSUE TITLE
Pre-build binaries + support for package managers like Brew

### ISSUE THREAD

**Issue by schickling** [Y2Z/monolith#11]
Would be great to pre-build binaries and support for package managers like Brew, apt, ...

**Comment by howardm** [comment]
I second this request.

It would be great for folks like me not sufficiently familiar with the app installation process, etc.

Howard

**Comment by TomOnGit** [comment]
+1. I'd like to use this project on Mac laptop, but I'm not sure how to use cargo. I tried http://macappstore.org/cargo/, but getting error (Error: Cask 'cargo' is unavailable: No Cask with this name exists.).

**Comment by alex-hofmann** [comment]
@TomOnGit 
> … No Cask with this name exists. …

This installation method is a bit outdated. If you would like to use Homebrew, try
```shell
$ brew install rust
```
Using `rustup` might be a better option [Rust: Install Rust](https://www.rust-lang.org/tools/install)

**Comment by jarmo** [comment]
Just installed it using brew and it is also stated in the [README](https://github.com/Y2Z/monolith/blob/master/README.md) that Snapcraft can be used on Linux.

I guess that this issue is resolved then?

**Comment by snshn** [comment]
Hey there @jarmo, I'll close this one when #110 is resolved, since the title of the issue mentions pre-built binaries. 🙂

**Comment by snshn** [comment]
As of now it's all done, monolith can be installed via Snapcraft, Homebrew, and there's a Windows executable being attached to every new release on the Releases page. Not sure about apt, maybe somewhere further down the road.
