### ISSUE TITLE
Put pre-built executables in releases page

### ISSUE THREAD

**Issue by rhysd** [Y2Z/monolith#110]
Hi,

This tool requires building from source to install. However, it requires Rust toolchain and it is sometimes hard for people. For example, those who are not familiar with Rust need to know Rust toolchain such as `cargo` only for installing this tool. And for another example, Windows user may need to prepare entire build toolchain for installing this tool because Visual Studio is not installed by default.

I want to suggest to put pre-built executables in releases page. Since we already have set CI, Travis CI and Appveyor can build executables and put them on the release page when making a new Git tag.

Fortunately I have experience to setup CI to deploy executables at [git-brws](https://github.com/rhysd/git-brws) so I can work on this. Only thing I cannot do is generating an encrypted deploy keys for both services due to permission:

- https://github.com/rhysd/git-brws/blob/master/.travis.yml#L75
- https://github.com/rhysd/git-brws/blob/master/.appveyor.yml#L64

How to generate them is described in below docs:

- Appveyor: [Generate auth token for GitHub release](https://www.appveyor.com/docs/deployment/github/), [store it in a secure variable](https://www.appveyor.com/docs/build-configuration/#secure-variables). It generates unique key for encrypted variable so I can use it for deploy config
- Travis CI: Using `travis` command, `travis setup releases` will make a config automatically and it includes key for the encrypted API key ([doc](https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token)). I can use it for deploy config

**Comment by snshn** [comment]
Hey there,

pre-built binaries were requested by multiple people while monolith was featured on HN, I believe it's still true that there's a certain level of demand for that method of obtaining the program. That group of lost users is sadly not visible. If it's possible to automate inclusion of those binaries, then I agree that it's definitely worth setting up.

Thank you for the links! I'll go through those instructions and generate the keys, then hand them to you... hopefully within 24 hours from now.

**Comment by rhysd** [comment]
Thank you. I did not intend to make you rush. So please try it when you are not busy :)

When generating a personal access token, please ensure that it has `public_repo` permission. Since keys for encrypted variables are secure, pasting them in a comment in this issue should be ok.

**Comment by snshn** [comment]
More like 24 days rather than 24 hours later, but here's what I have so far:

Encrypted AppVeyor token:

    +WxRHJ6YaCJfzCZMGZ+G40TrGOi4DnXpI6Sbb/T/f1R2HwP6zoiU9iqxeDq9g7Za

Encrypted Travis token:

    j2AXkuwn98/jkIPeQARw37lRehcd/CtWPKpW2ZjMOGFdiNhP7ggLXstaAi/PgYs+0/HgmTtJvEj0wJz0gtro1UUw1zWyaZWJ1i5jS2eg7ykjmsTUbULrZiAPd5tyDkRkn3QPLRiqrlmQ1wzlt3ueQnbsd/BEklJ2MDw6NM3JmV4vrw/BX6mrjnCYuJtW/yVFKoiioQK3Nc8f4YvOZELjuLsVPp7a3Kahtq2sd8it1UETfsWBxCMrU0sOVNTxe9yO1QI15nt4vwlTjqVo4cGWkPuE/Ugcb7mRt1fiU1yIQAxnOJJ8IlUoezS8ZkUHYnwxGAU8WODnwpKtg9ILM+1hS/v+XZupmXbrxwcRI0fT0Yjqz8uALBVZW8kwTTMDbg0Q6X0o/zIImWu/+et++6FsqsFqNud/ZuS8ZxuSmDtSj3g2bNcDycrdB60uRJtOvQXQ0aEdWLYxiVb0EjrveAm430Sql+MYd0nP1M6mmYB2K4vszCdxN9zMG687Y01PbBdJNu2M87a7TqW31LG1GZFnIg6MtHsCoUzUyRTMmUBkl3qhS2VJDAwTioB0vZ13MxVuRS29sSfMZ7ATAaYzF8m0/iJbMzpfV0Vjvsohk3ATm8OTsqqVevFmr1FBOj2KuWYoFdDOyX0k+0GvL9PJjv6h+OnX4TypL5pf+30gaudAoKA=

Both of the keys have only `public_repo` scope on them, but I believe that should be enough to have them add binaries to monolith releases -- please let me know if otherwise.

The keys belong to @monolith-machine-user (2FA protected), that account has been added to Y2Z's "Monolith" group that has write access to this repo. I couldn't add collaborators here as this repo is under an organization -- apparently GitHub only allows collaborators for non-org repos... but it should in theory work the same.

**Comment by snshn** [comment]
Now it's done. It's using GitHub Actions and currently uploads newly built monolith.exe as an additional artifact to every new release.
