### ISSUE TITLE
HTML differs per platform

### ISSUE THREAD

**Issue by JokerQyou** [Y2Z/monolith#113]
I encountered this very strange phenomenon. I have 2 platforms: a Linux server, and a macOS laptop. 

Now for this URL: `https://www.sohu.com/a/347860063_120094087`. I saved HTML files with monolith `2.1.2` using the same command:

```shell
monolith -o output.html -u "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.0 Safari/537.36" -I "https://www.sohu.com/a/347860063_120094087"
```

Now this is strange: the HTML saved on macOS, you can read the whole article. But for the HTML saved on Linux, there is a `read more` button in the middle, and the rest of the article is hidden with `display: none` via CSS class `.article-page .control-hide`. As can be seen in the following screenshot:

![image](https://user-images.githubusercontent.com/1465267/73610101-e7c2a100-460e-11ea-9f88-9e6fdf4cf51b.png)

On macOS I installed monolith via `homebrew`: `brew install monolith`. On Linux I built the binary within a docker container, the command is from [here](https://github.com/Y2Z/monolith/issues/45#issuecomment-530829666).

~~Notice that with the `docker run` command I actually built the binary from `master` branch. But I don't think it affects anything, because no source code has been modified since `2.1.2` was released.~~

Update: these are the last lines of the compiling output:

```
Compiling monolith v2.1.2 (https://github.com/Y2Z/monolith#1e834854)
    Finished release [optimized] target(s) in 6m 36s
  Installing /usr/local/cargo/bin/monolith
   Installed package `monolith v2.1.2 (https://github.com/Y2Z/monolith#1e834854)` (executable `monolith`)
```

So I guess the Linux binary was built from the `2.1.2` tag correctly.

On both platforms `monolith --version` returns `monolith 2.1.2`.

**Comment by snshn** [comment]
This is very peculiar... thank you for reporting this (I love puzzles!) Thankfully I have both GNU/Linux and macOS to recreate the scenario, I'll try it now and see what I get.

**Comment by snshn** [comment]
After trying to reproduce the behavior, I have to say that I failed to get different outputs from monolith on macOS and GNU/Linux: the document gets saved with the rest of the article hidden on both OSs. I'd like to recommend saving it with the `-c` flag, that way the page would lose its style, but as a side-effect you'll be able to see all its text (usually works fantastic for articles paywalled via CSS).

To solve the mystery, could you please do `diff` on both of those versions you get? That could give a good clue on why it's happening.

Thank you once again for the report.

**Comment by JokerQyou** [comment]
The diff is rather large.

![image](https://user-images.githubusercontent.com/1465267/73646294-1ba3d200-46b4-11ea-8dad-ea4503954972.png)

In case it helps, I've attached all the files. Diff command was `diff macos.html linux.html > diff.txt`.

[diff.txt](https://github.com/Y2Z/monolith/files/4147410/diff.txt)
[html_files.zip](https://github.com/Y2Z/monolith/files/4147412/html_files.zip)

The Linux version of monolith I used can be downloaded from [here](https://github.com/JokerQyou/selfbuild/releases/download/caddy-1.0.3/monolith-2.1.2).

**Comment by JokerQyou** [comment]
I think I have figured it out. My macOS laptop connects to this website directly, from China. But my Linux server does not. This website seems to put a `read more` button for foreign visitors only. If I force macOS to use proxy, the resulted HTML file also contains this `read more` button.

Glad to know monolith honors `HTTP_PROXY` env var, though.
