### ISSUE TITLE
Logo of CN NewYork Times missing

### ISSUE THREAD

**Issue by JokerQyou** [Y2Z/monolith#116]
The logo of CN NewYork Times is wrapped inside an SVG element. I don't know why they make it that way, but this results in missing logo in isolated HTML.

The live version, with normal logo:

![image](https://user-images.githubusercontent.com/1465267/73743256-16fd1d80-4789-11ea-8461-3a9e58e850ed.png)

Saved isolated HTML, with missing logo image:

![image](https://user-images.githubusercontent.com/1465267/73743475-9ee32780-4789-11ea-872b-a700e305903f.png)

**Comment by snshn** [comment]
Oh, that's very interesting... looks like the xlink:href needs to be parsed and converted into a dataURL. I'll look at what other attributes SVGs require to be parsed and fix this. Thank you for the report, @JokerQyou!

**Comment by JokerQyou** [comment]
Oh it's not `xlink:href`, that image has already got `src`.
