### ISSUE TITLE
Cannot build for raspbian (Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by smessing** [Y2Z/monolith#117]
Following the instructions to build this myself and I'm seeing:

```
cargo install --path .                                                                                                                          master
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to compile `monolith v2.1.2 (file:///home/pi/monolith)`, intermediate artifacts can be found at `/home/pi/monolith/target`

Caused by:
  no matching package named `native-tls-crate` found (required by `reqwest`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.2
```

Apologies if I've missed something obvious, this is my first time using `cargo`.

**Comment by snshn** [comment]
Hi Samuel,
I'm trying to figure out what's causing this, have a spare RPi 3B+ to reproduce the error. Thank you for reporting this.

**Comment by smessing** [comment]
Awesome! Thank you. I'm pretty new to Rust/Cargo but let me know if I can do anything to help.

**Comment by snshn** [comment]
Hi there Samuel,

I was able to build monolith from the master branch on raspbian with no errors. I used rustup and had to install libssl-dev.
The error that you're getting is likely related to some sort of network issue when cargo tries to retrieve the needed crate. I found a couple of similar issues for other rust projects and that's what people seem to suspect regarding this kind of errors, https://github.com/balena-os/balena-raspberrypi/issues/261

You could also try doing something like `mv Cargo.lock Cargo.lock.bak` and trying to build again, maybe it's some sort of issue caused by package versions

**Comment by bwestergard** [comment]
I'm encountering the same issue.

```
bjorn@bjorn-ThinkPad-T420:~/project/monolith$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
bjorn@bjorn-ThinkPad-T420:~/project/monolith$ make
    Updating crates.io index
    Updating crates.io index
error: no matching package named `native-tls-crate` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `reqwest v0.10.0`
    ... which is depended on by `monolith v2.1.2 (/home/bjorn/project/monolith)`
make: *** [Makefile:7: build] Error 101
```

**Comment by snshn** [comment]
I was able to cross-compile monolith on my Ubuntu machine using Cargo's built-in cross-compilation functionality:

```
rustup target add arm-unknown-linux-gnueabihf
git clone https://github.com/raspberrypi/tools.git rpi_tools
RUSTFLAGS="-C linker=rpi_tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc" cargo build --release --target=arm-unknown-linux-gnueabihf
target/arm-unknown-linux-gnueabihf/release/monolith -V
```

Could you please let me know if you're able to run the binary compiled that way on your Pi? If so, I'll include that into the CI/CD pipeline to release RPi artifacts along with Windows builds.

**Comment by snshn** [comment]
The [latest release](https://github.com/Y2Z/monolith/releases/tag/v2.2.6) includes a prebuilt binary for Raspberry Pi. I tested it on mine RPi 3B+, it works fine.

**Comment by whalehub** [comment]
@snshn Can you also make the pipeline make and upload an x86_64/AMD64 executable with every new release?

**Comment by whalehub** [comment]
@snshn Thanks! I'd love to add support for monolith in [ginstall.sh](https://github.com/whalehub/ginstall.sh) once that's done.
