### ISSUE TITLE
Doesn't seem to handle lazy loaded images

### ISSUE THREAD

**Issue by logix2** [Y2Z/monolith#16]
Example URLs:
[https://appelsiini.net/projects/lazyload/fadein/](https://appelsiini.net/projects/lazyload/fadein/)
[http://jquery.eisbehr.de/lazy/example_basic-usage](http://jquery.eisbehr.de/lazy/example_basic-usage)

These are the only 2 URLs I actually tried  to see if Monolith can handle lazy loading, and it fails for both.

**Comment by snshn** [comment]
Hi @logix2 

thanks to @Alch-Emi's efforts, if you use the latest code from the `master` branch, both of those URLs now will get saved with high-res images embedded, both with and without JS (the `-j` flag). Please let us know if it works now. Thanks for reporting the issue!
