### ISSUE TITLE
Doesn't save images on this page?

### ISSUE THREAD

**Issue by mattl** [Y2Z/monolith#17]
https://stevie.boston/WebObjects/Flipper.woa/wa/

**Comment by vflyson** [comment]
It worked for me, the resulting file ended up being 19M in size since many of them are GIFs. Did you see a timeout message or some sort of error in the terminal, or the images just couldn't render when you opened the page?

**Comment by mattl** [comment]
./monolith https://stevie.boston/ > stevie3.html -- 21K file.
./monolith https://stevie.boston/WebObjects/Flipper.woa/wa/ > stevie2.html -- 21M file.

So is it not handling the redirect correctly?

**Comment by vflyson** [comment]
It seems to be definitely a bug in monolith. The original URL (https://stevie.boston/) is currently being used to compose the full URL to retrieve assets on this page https://stevie.boston/WebObjects/Flipper.woa/wa/ which results in images being retrieved as 404. I'm looking into how best solve this issue with redirects and URL resolution, thank you for the extensive info @mattl
