### ISSUE TITLE
Download pages with untrusted ssl

### ISSUE THREAD

**Issue by lukas-mertens** [Y2Z/monolith#175]
Sometimes it is useful to download websites with untrusted ssl, e.g. during development, for archiving abandoned sites with expired ssl certificates etc. Especially the last use case is very important, as an expired ssl certificate is a big sign, that the site could go down in the future. That doesn't work in the current version though:

```bash
monolith https://expired.badssl.com/ -o badssl.html

thread 'main' panicked at 'Could not retrieve assets in HTML: reqwest::Error { kind: Request, url: "https://expired.badssl.com/", source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1913 }]))) }, X509VerifyResult { code: 10, error: "certificate has expired" })) }', src/main.rs:76:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My proposal would be, to add a command line flag, to explicitly allow untrusted ssl certificates.

**Comment by snshn** [comment]
Could you please try running monolith with the `-k` flag and let me know if it solves the issue?

**Comment by snshn** [comment]
I assume using the `-k` flag has worked, please let me know otherwise and I'll reopen this issue.

**Comment by lukas-mertens** [comment]
Hey, sorry for the late reply. Yes, it works! I can't believe that I was too stupid to find that in the docs. I actually read the docs first, but it seems like I skipped it. According to git blame it was already in the documentation 9 month ago... I mean, wtf? Am I in a parallel universe or something? It's very clearly documented, I can't believe I missed it... SORRY for the stupid issue!

**Comment by snshn** [comment]
It's all good, please don't worry. That option is very hard to describe and I myself remember having hard time finding it in curl and wget, since there's a million different descriptions and use-cases that that option may have. Glad it worked out well for you!
