### ISSUE TITLE
Readme page installation doesn't mention Windows

### ISSUE THREAD

**Issue by billforsternz** [Y2Z/monolith#198]
There are installation instructions for MacOS and Linux. At first blush I assumed Monolith didn't work in Windows. Then I noticed  "Windows - Passing", and later I found that monolith.exe was in the Release .zip. But it would be better to have a one line explanation in a Installation > Windows section. Thanks, great work.

**Comment by HarishSTOnline** [comment]
Hi @billforsternz, how you made it to work in Windows. I have downloaded the .exe file from the Release and tried installing, But nothing actually happens. It would be great if you can share you experience.

**Comment by snshn** [comment]
Hey,

I'm working on adding monolith to chocolatey, once it's there I'll be able to add instructions for installing it on Windows using choco. Aside from that I'll add a bit of information regarding pre-built binaries to the README. Thank you.

**Comment by snshn** [comment]
@HarishSTOnline monolith is currently a command-line utility, so you'll need to put it either in your PATH and use terminal emulator (I think there are programs called "Console" and "PowerShell" on Windows that should suit your needs).

**Comment by HarishSTOnline** [comment]
Thanks @snshn. I got it to work by following your guidance. Thank you! ❤️
