### ISSUE TITLE
Make it parse CSS as well, replacing url(...) with url(data:...)

### ISSUE THREAD

**Issue by snshn** [Y2Z/monolith#2]
That shall include stuff within style=""

**Comment by calexicoz** [comment]
This would be a nice addition, as many sites use icon fonts (Twitter...).

Thanks for this great tool in any case :)

**Comment by knidarkness** [comment]
@snshn I could work on this if you don't mind and that's still relevant?

**Comment by snshn** [comment]
It's still relevant, yes, and any help would be extremely appreciated.
I've been looking into servo's rust-cssparser, seems like a solid library for parsing and manipulating css. Perhaps the hardest part here would be css' `import`.

**Comment by knidarkness** [comment]
Okay, then I`ll do some research and will try to start on this weekend.
