### ISSUE TITLE
Saving tweets - Twitter's doing redirects and JS detection that thwarts monolith

### ISSUE THREAD

**Issue by paul-hammant** [Y2Z/monolith#204]
`monolith -I -j -u "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15" <URL-to-tweet> -o saved_it.html`

Turning Javascript off in the browser redirects you to the mobile site. Essentially, the same URL with a "mobile." prefix on the domain. So that saves via monolith, but when the page loads up again from disk, it presents a "wanna redirect" challenge:

![image](https://user-images.githubusercontent.com/82182/88452929-a8a53800-ce5a-11ea-9d13-ba7fb0746064.png)

Not sure if I'm outside the design intentions of monolith or not...

**Comment by snshn** [comment]
You could try pretending being a robot, e.g. `monolith -I -j -u "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" <URL-to-tweet> -o saved_it.html`
This way you'll save that page in a plain HTML format (that you can see being used for google search page caches and in The Internet Archive's Wayback Machine).

**Comment by paul-hammant** [comment]
That worked. I had to add `<meta charset="utf-8" />` to the <head> section to make it render correctly in Chrome, but it was good.

**Comment by snshn** [comment]
Great to hear! I'll look into the charset issue to be improved.
