### ISSUE TITLE
Permission Denied in Ubuntu 18.04

### ISSUE THREAD

**Issue by HarishSTOnline** [Y2Z/monolith#209]
Hi Everyone,

I am almost sure that this has something to do with Permission of directories. But I am unable to rectify it.
I have installed monolith using snap on a Ubuntu server. Now _the command is working fine and the HTML file is generated at the_ **HOME(~) directory**. But whenever I run the command in any other directory (Like inside a web application directory), I am getting the following error. 

> sudo RUST_BACKTRACE=full monolith https://google.com -o google.html
thread 'main' panicked at 'Could not prepare output: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:89:22
stack backtrace:
   0:     0x5638fdc87294 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x5638fdc87294 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x5638fdc87294 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5638fdc87294 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5638fdca9bec - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:     0x5638fdc812d3 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:     0x5638fdc89ad5 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5638fdc89ad5 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5638fdc89ad5 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:     0x5638fdc89822 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:     0x5638fdc8a132 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:     0x5638fdc89d1b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x5638fdca7991 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:     0x5638fdca77b3 - core::option::expect_none_failed::ha9782a6ef355446f
                               at src/libcore/option.rs:1211
  14:     0x5638fda5492d - monolith::main::h3101ccf790cf9397
  15:     0x5638fda54dc3 - std::rt::lang_start::{{closure}}::h46c8f19152d86678
  16:     0x5638fdc89bf3 - std::rt::lang_start_internal::{{closure}}::h9a4aa16acf1cdc99
                               at src/libstd/rt.rs:52
  17:     0x5638fdc89bf3 - std::panicking::try::do_call::h0b6fc9f6090c1e2b
                               at src/libstd/panicking.rs:303
  18:     0x5638fdc8d957 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  19:     0x5638fdc8a71c - std::panicking::try::h9eaeeaa81242ec77
                               at src/libstd/panicking.rs:281
  20:     0x5638fdc8a71c - std::panic::catch_unwind::h07d504c1b691e8fb
                               at src/libstd/panic.rs:394
  21:     0x5638fdc8a71c - std::rt::lang_start_internal::hcea4e704875ab132
                               at src/libstd/rt.rs:51
  22:     0x5638fda54db2 - main
  23:     0x7ffb6da93b97 - __libc_start_main
  24:     0x5638fda4acda - _start
  25:                0x0 - <unknown>

I have given 775 and 777 for the directory and tested whether it is working, but it still gives the same error. The command was working fine in my Local environment which is Windows.
I am using Ubuntu 18.04 on my server. Can someone help me out? It seems this is a simple issue but I could not solve it. I have tried searching the issue queue but no related issues found. Thank you.

**Comment by HarishSTOnline** [comment]
I am now getting the `{ code: 2, kind: NotFound, message: "No such file or directory" }`, when trying to run the command outside HOME or its sub-directory. Basically, I am not able to create the HTML file other than HOME or its subdirectory. 

For Example:

monolith https://google.com -o /var/www/google.html gives me the above error.

**Comment by snshn** [comment]
Hi Harish,

so the thing with Snaps is that they're isolated. If you do `which monolith` it'll show you that it's located at `/snap/bin/monolith`, then `ln -hl /snap/bin/monolith` will print this:
> `lrwxrwxrwx 1 root root 13 May 17 20:05 /snap/bin/monolith -> /usr/bin/snap`
So in a nutshell when you run monolith installed from a snap, it runs it via /usr/bin/snap, not directly. This way /usr/bin/snap is able to sandbox and prevent programs from e.g. modifying files outside of your home directory, which could be a security issue.
Now, on my Ubuntu, monolith is also installed via Snapcraft, and it works well writing files into any directory. That's the part that's surprising to me, but I did see reports of this issue affecting others, so perhaps it could be something to do with that.
I'd say the easiest way to solve that would be removing the snap of monolith and re-installing it from source via rustup.
Meanwhile I'm gonna look into solving that issue in monolith's snap.

**Comment by HarishSTOnline** [comment]
Thank you @snshn, I will try with rustup!

**Comment by HarishSTOnline** [comment]
Hey shshn, 

Thanks for this wonderful tool! From your suggestion, I have installed it with Rustup! Working great... Thanks again! Closig this issue.
