### ISSUE TITLE
How to support other charset？

### ISSUE THREAD

**Issue by tda7088** [Y2Z/monolith#212]
Hello, how to support non-utf8 strings? Such as gbk。
`<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="content-type" content="text/html;charset=GB2312">
<meta http-equiv="Content-Language" content="utf-8">
<meta content="all" name="robots">
<title>��������ѪҺ�������ŶԵ����ҳ�--��ʷƵ��-������</title>
<meta name="keywords" content="������ 1950�� ѪҺ ���� �� ������Ա ���� ���� �й������ž�����Ұս�� �Ĺ�,��������ѪҺ�������ŶԵ����ҳ�--��ʷƵ��">
<meta name="description" content="����2020��Ԫ��ǰϦ������ʡ�����к��Ͻֵ�����ʢ������ͬ־������ȥ�����ϵ�Ա��������������Ϥ�����ӣ��������ر��ģ������Լ������İ����������ɵ�ͬ־���ó�ο�ʽ�ʱ����ȴһ�����࣬��Ȼ�ܾ������������,��������ѪҺ�������ŶԵ����ҳ�--��ʷƵ��">`

**Comment by snshn** [comment]
Hi @tda7088,

it needs to be implemented in the program itself, has to be detected via HTTP headers and via META tags in the document. Could you please let me know what other non-utf8 encodings aside from GBK you believe are necessary to be supported by monolith?

**Comment by tda7088** [comment]
Thank you for your reply. Because monolith saves HTML as utf8 character set by default, some pages in other character sets cannot be reversely converted and cannot be restored after conversion. If monolith can automatically determine the character set or provide options to specify the character set, it will be more powerful. Thanks again for your reply

**Comment by tda7088** [comment]
I found another software that supports gbk encoding, https://github.com/markusmobius/nodeSavePageWE

**Comment by tda7088** [comment]
The speed is relatively slow, not as good as the monolith, I will try to modify the character set when the monolith saves the file. First contact with rust

**Comment by tda7088** [comment]
I am not familiar with rust grammar, and the writing is relatively poor, so I can barely use it.
`//dom = html_to_dom(&String::from_utf8_lossy(&data));
let html=String::from_utf8_lossy(&data);
if html.contains("=GB2312")|html.contains("=GBK")|html.contains("=GB18030") {
    //eprintln!("data3:{}", GBK.decode(&data, DecoderTrap::Strict).unwrap());
    let html0=GBK.decode(&data, DecoderTrap::Strict).unwrap();
    let html1=&html0.replace("=GB2312", "=UTF8").replace("=GBK", "=UTF8").replace("=GB18030", "=UTF8");
    //eprintln!("data4:{}", html1);
    dom = html_to_dom(html1);
}else{
    dom = html_to_dom(&html);
}

`

**Comment by snshn** [comment]
That gives me a good idea of how to deal with those charsets, thank you. I'll add detection of content-type HTTP header and deal with meta-tags and conversion, I believe that should be enough for most non-UTF8 cases.

**Comment by snshn** [comment]
This should work now. If you get a chance, could you please check the `master` branch and run the code from there via `cargo run -- <options> <url>`? I'm going to make a new release by the end of the week.

**Comment by JokerQyou** [comment]
I did not have a chance to test GBK encoding, but monolith (at least in 2.5.0) did not work well with GB2312 encoding. For Asian users, these are the common encoding types for texts, but not sure if all of them are used to form webpages:

- GBK, GB2312, GB18030 for mainland China (Simplified Chinese). GB18030 is almost UTF-8.
- Big5 for regions using Traditional Chinese like Hongkong, Taiwan, etc.
- JIS, Shift-JIS for Japanese.

For GB* series encodings (charsets), most of them came from legacy CMS. Here's an example: http://finance.people.com.cn/n1/2021/0607/c1004-32124148.html . If you save it with monolith 2.5.0, you can see all the text are not displayed correctly.

**Comment by snshn** [comment]
Hi there @JokerQyou,

thank you for letting me know that the issue still persists.

I just finished implementing support for processing encodings other than UTF-8.  There's also a `-C` option that makes it possible to save the document using preferable charset, no matter what the original document used, e.g. like this: `monolith -C utf8 https://.../gb2312.html -o utf8.html`.

The release version `2.6.0` is out and should be available via Brew and other software package management tools in a day or two.

It appears to be finally fixed for good, @tda7088 

Thanks again!

**Comment by JokerQyou** [comment]
Great! I've just tested the URL in my previous comment, and it's working now. The `-C` option to rewrite the file with specified encoding also works as expected. Thanks for your efforts!

**Comment by JokerQyou** [comment]
Great! I've just tested the URL in my previous comment, and it's working now. The `-C` option to rewrite the file with specified encoding also works as expected. Thanks for your efforts!

**Comment by snshn** [comment]
You got it!
