### ISSUE TITLE
Multiple pages into one?

### ISSUE THREAD

**Issue by DillFrescott** [Y2Z/monolith#223]
I have a small website with 2 separate pages. I've managed to compress them down to just two .html files using Monolith.

Is there a way to combine these 2 html files into one with two distinct pages?

I've seen it done before where it adds a #something to the end of the url for the other page that is displayed.

This is a really cool project btw!

**Comment by snshn** [comment]
Hi there Cross!

Interesting case, good question... I'd use something like [this](https://github.com/Y2Z/data.sh) to convert one of the HTML files into a data url, and then edit href within the first HTML document to be set to that giant data: link. It should work.

**Comment by DillFrescott** [comment]
I'll try that. Sounds like a good idea!

By the way, I've been messing with base64 data url's and i want to use one in a url shortener.

But the shortener needs https://  or http:// in front of the data url in order to work.

But this breaks the data url.

Is there a way to have a simple html file or javascript that I can host on github pages take the data url and remove the http:// and domain name?

So it would look like https://example.github.io/redirect.html and then at the end would be a data url like:

data:text;base64,VGhpcyBpcyBhIHRlc3Qgb2Ygc29tZSB0ZXh0Lg0KDQpIZXJlIGlzIGFub3RoZXIgcm93IQ==

I know nothing about coding lol this is so difficult for me!

**Comment by DillFrescott** [comment]
I'll try that. Sounds like a good idea!

**Comment by snshn** [comment]
Did it work?

**Comment by DillFrescott** [comment]
Sort of. I'm not good with html lol.

It definitely would if I knew why I was doing haha!

I'm fine with 2 html files that's still not a lot for a full website with 2 pages.

**Comment by snshn** [comment]
You just have to find `<a href="...">Link Name</a>` and replace whatever is within "" (ellipses in the example) with a data URL (data:...). That's pretty much it.

**Comment by DillFrescott** [comment]
Ah. But the issue is that there are a couple buttons that lead to the second page. One at the top bar and another towards the bottom of the page.

I didn't want to paste the full 7. Something MB of base 64 for each button and triple the size of the file :(

**Comment by DillFrescott** [comment]
I tried creating a reference to it using a div container I think it's called so I only had to paste it once. But it didn't really work that well.

**Comment by snshn** [comment]
If you make a repo with those two files I'll gladly show how to merge them in a PR.

**Comment by DillFrescott** [comment]
I might do that in the future but I'm fine for the moment.

There is something that I was trying to figure out how to do with no luck though.

I need a static .html script page that can take a base64 text url that is at the end of the link and display its content.

For example 'https://myrepo.github.io/index.html' and then either a ? Or a # (AI don't know which works) so like:

'https://myrepo.github.io/index.html?=data:text;base64,InsertStringHere'

**Comment by DillFrescott** [comment]
So when you click the link it just processes it and displays the base 64 text just like you put the data url directly into your browser

**Comment by DillFrescott** [comment]
This way I can use a url shortener with it. 

Because most url shortener do not allow data links. The links must start with http or https

**Comment by snshn** [comment]
That's clever! There could be a limit set on the URL length in URL shorteners. ? sends  data to the server, so # would likely be the way to  go.
