### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DillFrescott** [Y2Z/monolith#224]
Would it be feasible to be able to download and convert videos into base64 with the rest of the site?

That would be a neat flag option.

Also a way to get past Cloudflare's JavaScript challenges. (If it can't already do that)

**Comment by snshn** [comment]
Video file support is an upcoming feature; not all videos can be easily retrieved though, some are streamed and not a single media file.

Cloudflare would require JS support, I'm working on it as well... currently only SingleFile can bypass Cloudflare, to my knowledge.

**Comment by DillFrescott** [comment]
Ok. Sounds like some cool upcoming features!

**Comment by DillFrescott** [comment]
By the way I don't think SingleFile can bypass a Cloudflare js challenge. I think it's the browser doing the work, then after you have passed the challenge, it just downloads what you see and has been transferred to you.

I could be wrong tho.

**Comment by DillFrescott** [comment]
Aren't js challenges basically math in javascript that it needs to do? Then it assigns a special cookie if you complete it?

**Comment by DillFrescott** [comment]
That's at least how I assumed it works...

**Comment by snshn** [comment]
I think so... sometimes it has a CAPTCHA challenge, that'd require a UI, but just JS + Cookie can be easily emulated in headless mode
