### ISSUE TITLE
Idea for saving video with Monolith

### ISSUE THREAD

**Issue by DillFrescott** [Y2Z/monolith#225]
This might sound crazy, but is there a way to save the videos from a webpage as an actual mp4 file thats in a container named something.html?

Much like how renaming a .zip file to .jpg turns it into a picture (tho un-openable) but changing it back to a .zip allows it to be opened again. Could you make a .zip file named .html with the video inside, and put the html code at the "top" so to speak so when you try to open it, it reads the html code still, but it's technically still a container with the video data stored inside which it can reference?

No idea if this is stupid and impossible but it occurred to me. Might as well ask :)

**Comment by snshn** [comment]
You've described exactly what SingleFileZ does, https://github.com/gildas-lormeau/SingleFileZ

That makes the HTML no longer available to grep, and makes the document require JS support to be viewed, hence can't really implement that for monolith, no matter how cool the idea seems to be.

**Comment by DillFrescott** [comment]
Whoa that's weird! Gotcha tho, guess it doesn't hurt to ask =P
