### ISSUE TITLE
Anyway to adjust the viewport size?

### ISSUE THREAD

**Issue by npearson72** [Y2Z/monolith#238]
Puppeteer has a function to pass in the following params:

```
page.setViewport({ width: 2000, height: 1000 })
```

This helps in cases where sites use JS to make layout adjustments based on viewport size. Having control over the size or a default size that's very large would be helpful.

**Comment by snshn** [comment]
No, not possible, no viewports here. Puppeteer runs Chromium in headless mode, while Monolith doesn't have any browser underneath, it simply resolves and embeds assets.

I agree that it could help saving some sites, perhaps I'll try to add optional browser engine at some point, will definitely implement the sizing setting then.

**Comment by npearson72** [comment]
Thanks!
