### ISSUE TITLE
Can I add a related project?

### ISSUE THREAD

**Issue by liamwarfield** [Y2Z/monolith#257]
Hey I made a project that glues Monolith (local document storage), Tantivy (An offline search engine), and youtube-dl into a CLI tool! I was wondering If I could Add it to your "Relate Projects" section?

https://gitlab.com/fisherdarling/monk

**Comment by snshn** [comment]
Hi there,

yes, absolutely, please go for it!  Thank you for asking.

**Comment by snshn** [comment]
@liamwarfield please let me know if what's in #259 is good, I'll merge it in and close this issue
