### ISSUE TITLE
XML serialization

### ISSUE THREAD

**Issue by bmix** [Y2Z/monolith#26]
Hello,

great project!

Wouldn't serialization as XHTML5 add to the aspect of "ease of use" and "archival" by allowing to place queries against the static X(HT)ML files using XPath utilities like Saxon, BaseX or Xidel? That would make a dream come true, for me.

**Comment by bmix** [comment]
Hello @vflyson,

you are right. It could be piped to an external program like ['tidy'](http://www.html-tidy.org/), '[tagsoup](http://vrici.lojban.org/~cowan/XML/tagsoup/)' or ['validator.nu'](https://about.validator.nu/htmlparser/)

I wonder what I had on mind, when requesting this feature, since I, usually use 'tagsoup' or 'validator.nu' for such purposes myself. It may have been, that I wanted ease of use by having an all-in-one solution. But I agree with you. Piping it will deliver the same result, I guess. This is a classic facepalm on my side. Sorry.

If you don't mind, I close this as resolved.

**Comment by vflyson** [comment]
It's all good @bmix. It could still be a useful feature, I'll keep it in my notes.
