### ISSUE TITLE
Hi Tobias,

### ISSUE THREAD

**Issue by AhmedShah63** [Y2Z/monolith#280]
Hi Tobias,

Thank you for sharing your code and making this PR!

The problem I see with this approach (and the main reason Monolith to this day doesn't have that functionality) is that while specifying User-Agent globally is okay, setting either cookies or basic auth the same way is a major security issue.
Both cookies and basic auth are tied to domain name when you use your browser, so when you visit the website, those cookies don't get sent to servers that have their content linked on that website, they're securely contained to only be sent to requests made to that domain name the website is located on.  But attaching those headers to the same `reqwest` instance and then pulling resources from different servers, sending those headers along with those requests, has basically leaked your security credentials for your Wiki to them, sorry 😢

_Originally posted by @snshn in https://github.com/Y2Z/monolith/issues/268#issuecomment-866427743_

**Comment by Tobi823** [comment]
Sorry for the late response,

I thought I would find time to improve the pull request further (by supporting the Netscape HTTP Cookie File format).

I will close this PR for now (maybe I will open it again)
