### ISSUE TITLE
Panic when saving

### ISSUE THREAD

**Issue by mrzv** [Y2Z/monolith#293]
Saving <https://knowablemagazine.org/article/food-environment/2021/what-world-can-learn-britains-humble-hedge> with version 2.6.1 results in a panic (from `unwrap`ping an `Err`).

**Comment by snshn** [comment]
Greetings Dmitriy!  Thank you for reporting the crash.  I'm currently working with the author of the networking crate that monolith uses for retrieving files in order to fix it, it seems to be a bug associated with decoding gzip in that library.

**Comment by mrzv** [comment]
Thanks for the update, and thanks for investigating.

**Comment by snshn** [comment]
A bit late, but found the issue.  That file is being served with quite rare `brotli` compression algorithm, support for which I'm currently adding along with `deflate`.  The fix will be in the next release.  Thank you for reporting this issue!
