### ISSUE TITLE
Repeating an option shouldn't throw an error but use the last instance

### ISSUE THREAD

**Issue by gd4c** [Y2Z/monolith#295]
Repeating an option like `-o doc.html` shouldn't throw an error but use the last one. This is conventional and useful.

**Comment by snshn** [comment]
Hi @gd4c,

I'm not entirely sure how conventional that behavior is... it looks like a very forgiving mode for CLI, and I'd say 99% of mature tools that I use (most are of course from GNU), they seem to throw an error whenever there's a syntax error/mistake.  In my experience, CLI modes tend to be way more strict than GUI ones.
