### ISSUE TITLE
How to save a webpage with "space" in name?

### ISSUE THREAD

**Issue by JdeV987** [Y2Z/monolith#296]
I can not save a webpage with a blank (space) in the name, how do I do it?
For example, if I do this:  
monolith https://github.com/Y2Z/monolith and other/issues and answers/new > test.html   ,
it says:
error: Found argument 'other/issues' which wasn't expected, or isn't valid in this context

**Comment by snshn** [comment]
Hi there @JdeV987!

In terminals, spaces are separators of arguments, so you have to either use `%20` or just wrap the URL into quotation marks, e.g.:

`monolith 'https://github.com/Y2Z/monolith and other/issues and answers/new' > test.html`
