### ISSUE TITLE
Start using minimizers for HTML, JS and CSS to save space

### ISSUE THREAD

**Issue by snshn** [Y2Z/monolith#3]
Make an option to disable them in case somebody would like to decode base64 at some point and dig through plaintext assets

**Comment by knidarkness** [comment]
@snshn , do you think that would do any significant impact? As for now most of the size is used for storing base64 values of images or other assets and there's really not to much that we could do about that, IMO?

**Comment by snshn** [comment]
@knidarkness most likely not, and wouldn't be worth implementing; I think this idea crossed my mind when I was trying to plan features for monolith's prototype (originally in Node), but as the tool became more mature I obtained more feedback, and it's more likely that in order to slim output files down, monolith will need to get a max asset size flag (e.g. `monolith -m 1M https://github.com...`) to skip media content (images, audio, video) that exceeds 1024KB in size. I'll close this issue now, thank you
