### ISSUE TITLE
it goes white screen after 10 seconds (when saving reddit pages)

### ISSUE THREAD

**Issue by KonstantinDjairo** [Y2Z/monolith#305]
i tried to save reddit web pages and it works... at least until 10 seconds and all goes white, i asked some people to try too, because i the problem would be my browser,but it was not (i use chromium) and they say to have the same problem.

a screenshot:
> https://imgur.com/a/XMeC31b

**Comment by snshn** [comment]
Hi there Konstantin,

my wild guess would be some kind of JS code messing with the saved document.  Could you please try saving it with `-j` flag?  `-jn` could work as well, if just `-j` doesn't do anything.  Please let me know if it helps.

**Comment by KonstantinDjairo** [comment]
> Hi there Konstantin,
> 
> my wild guess would be some kind of JS code messing with the saved document. Could you please try saving it with `-j` flag? `-jn` could work as well, if just `-j` doesn't do anything. Please let me know if it helps.

thank you, this worked as well!!
