### ISSUE TITLE
error trying to connect: bad protocol version

### ISSUE THREAD

**Issue by cbluth** [Y2Z/monolith#306]
I am having an issue with a specific URL:
- https://wiki.theory.org/index.php?title=BitTorrentSpecification
- or
- https://wiki.theory.org/BitTorrentSpecification

i keep getting this error:
```
$ monolith  'https://wiki.theory.org/index.php?title=BitTorrentSpecification'
https://wiki.theory.org/index.php?title=BitTorrentSpecification (error sending request for url (https://wiki.theory.org/index.php?title=BitTorrentSpecification): error trying to connect: bad protocol version)
Could not retrieve target document
```

```
$ uname -a
Darwin localhost 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
$ monolith --version
monolith 2.6.1
```

**Comment by snshn** [comment]
Hi Cobin,

thank you for reporting this.

Seems to work fine with 2.6.1 on GNU/Linux... now will test macOS... confirmed, getting the same exact error as you do on macOS.   I've updated `reqwest` dependency in master, haven't made a new release yet, but if it still happens on macOS with that new version of the library, I'll dig into what's causing it and make sure it's fixed.

Will report here once done.

**Comment by sturmery** [comment]
Seems to be working now with monolith v2.6.2.  Was probably some bug in one of the crates/3rd-party dependencies, all those got updated to latest versions for 2.6.2.

Please let me know if it works for you now on macOS.

**Comment by snshn** [comment]
The bug seems to be gone now, please feel free to reopen if you encounter this issue again.

**Comment by cbluth** [comment]
this issue is back, same url same error
