### ISSUE TITLE
Rewrite "srcset"

### ISSUE THREAD

**Issue by I-Al-Istannen** [Y2Z/monolith#32]
## Problem
Sites can use the [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset) attribute to specify an image's source. This tag is not rewritten, causing the monolith-ed pages to still perform a network request and rely on the remote server.

## How to reproduce
Copy the following HTML into a file and serve it (e.g. via `python -m http.server 8080`).
Then run monolith on it and have a look at the result.
```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Test for monolith</title>
    </head>
    <body>
        <h1>This is an image with a <strong>src</strong> attribute:</h1>
        <img src="https://upload.wikimedia.org/wikipedia/commons/0/0b/Cat_poster_1.jpg" width="500px">

        <h1>This is an image with a <strong>srcset</strong> attribute:</h1>
        <img srcset="https://upload.wikimedia.org/wikipedia/commons/0/0b/Cat_poster_1.jpg" width="500px">
    </body>
</html>
```
For me monolith will rewrite this to:
```html
<!DOCTYPE html><html lang="en"><head>
        <meta charset="utf-8">
        <title>Test for monolith</title>
    </head>
    <body>
        <h1>This is an image with a <strong>src</strong> attribute:</h1>
        <img src="<base64 that nearly kills vim>" width="500px">

        <h1>This is an image with a <strong>srcset</strong> attribute:</h1>
        <img srcset="https://upload.wikimedia.org/wikipedia/commons/0/0b/Cat_poster_1.jpg" width="500px">

</body></html>
```
As you can see, the srcset is still present and linking to an external image.

## Caveats
The `srcset` can contain multiple images (by design). Which one should be saved?

## Monolith version
[625c529cf1409848aa3ce42a74991d0d69c75d88](https://github.com/Y2Z/monolith/commit/625c529cf1409848aa3ce42a74991d0d69c75d88) ~ Merge pull request #21 from Y2Z/author-robatipoor

**Comment by vflyson** [comment]
Thant's such a good submission, thank you.

I've just implemented support for `srcset` within `source` children of `picture` tags, will take care of `srcset` within `img` tags next, including those that contain a list of images, rather than just one.

**Comment by knidarkness** [comment]
@snshn is that still in 'todo' state? If so, I could help with that.

**Comment by snshn** [comment]
It still is, I'd gladly appreciate your help on this one.
I've looked into using regular expressions and studied servo's code but their approach seems to be too monstrous for me to use as a case for study.
