### ISSUE TITLE
Unsupported document media type

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [Y2Z/monolith#320]
[This check](https://github.com/Y2Z/monolith/blob/7c61b462ddd8f3b0e982a8cba229b1ddf371457f/src/main.rs#L183) is probably too aggressive and definitely lacks any mechanism to override it.

```
$ monolith https://www.devever.net/~hl/strawberry_farewell
https://www.devever.net/~hl/strawberry_farewell
Unsupported document media type
```

**Comment by snshn** [comment]
Good point, if the browser is capable of opening the page, monolith should save it without complaints.  The check will be removed from the next release, thank you for reporting this bug.

**Comment by snshn** [comment]
The patch is done and is about to get merged into `master`.

The bad news is that Monolith seems to be unable to properly parse and save XHTML documents.
I'll open new issues to address this flaw.

Thank you for reporting this, I know what needs to be done to get it all fixed.

I'll try to make a new release within a couple of hours, that will include this latest fix.
