### ISSUE TITLE
Save pages with login

### ISSUE THREAD

**Issue by norawa1973** [Y2Z/monolith#325]
How to save pages that require login?

**Comment by snshn** [comment]
If you log in using Chrome (Chromium), you could follow instructions in the "Dynamic content" section here: https://github.com/Y2Z/monolith#dynamic-content
Just be sure not to use the "--incognito" flag, to make the browser uses the same session/identity.

**Comment by snshn** [comment]
You can also save the page as HTML + assets using your browser, and then run Monolith on that HTML file to make it monolithic.
