### ISSUE TITLE
Add a verbose flag to track large site downloads

### ISSUE THREAD

**Issue by antonioaguilar** [Y2Z/monolith#33]
Nice tool but it needs more work. Add a verbose flag to track large site downloads.

**Comment by vflyson** [comment]
Thank you for the suggestion.
What's your opinion on this style of output?
```
$ monolith https://news.ycombinator.com > hn.html
[ https://news.ycombinator.com -> https://news.ycombinator.com/ ]
[ https://news.ycombinator.com/news.css?ASVGiGQi7APkR34EEOvF ]
[ https://news.ycombinator.com/favicon.ico ]
[ https://news.ycombinator.com/y18.gif ]
[ https://news.ycombinator.com/s.gif ]
[ https://news.ycombinator.com/hn.js?ASVGiGQi7APkR34EEOvF ]
```

**Comment by vflyson** [comment]
Merged that one in to at least have some kind of verbosity for now, as it does not affect the data sent through stdout. The format should perhaps be improved later. I'll close this issue once there's either a -v or a -s flag in place to toggle the program's verbose/silent mode.

**Comment by antonioaguilar** [comment]
Looks good, but thinking about it ... perhaps monolith should always output the downloading status and only use the flag to disable the verbose output, similar to what wget and curl do.

**Comment by vflyson** [comment]
I too, am leaning towards adding a `-s` flag, since pulling the whole website usually takes a long time, and it's rather creepy when a program doesn't talk for a long period of time.
