### ISSUE TITLE
Query: Can monolith recursively follow links in a single domain and create a monolith for them ?

### ISSUE THREAD

**Issue by Haiz14** [Y2Z/monolith#330]
I tried 
```bash
/s/6/docs[124]►monolith "https://lyrics.github.io/db/P/Portishead/*" -o portishead-roads-lyrics.html
https://lyrics.github.io/db/P/Portishead/* (404 Not Found)
Could not retrieve target document
``` 
But it doesn't work

**Comment by snshn** [comment]
Oh, I wish.

While technically possible, it'd result in a HTML file so big, that no browser will be able to open it without crashing (last time I tried implementing it, the .html file was hundreds of megabytes, even Chrome couldn't open it).

The only way to go about this is retrieving the list of links and then using monolith on each of them, saving each page separately.

I'll look into iframes and potentially using MHTML format for storing assets shared between multiple pages outside of the iframe, that could work in theory.

**Comment by snshn** [comment]
I believe https://www.httrack.com/ or similar could do a much better job archiving interlinked pages.

**Comment by Haiz14** [comment]
What if the final bundle is an SPA with pages being loaded on page request.

To achieve goal: saving a (multi-article) code documentation for offline use. 

the output dir 
```fs
pages/ index.html 
```
