### ISSUE TITLE
What does the -I flag do?

### ISSUE THREAD

**Issue by catfromplan9** [Y2Z/monolith#334]
Description is unclear

**Comment by snshn** [comment]
Hi cat,

thank you for the question.  It commands the browser that the saved document can load resources only from data: URLs and from inside its own HTML, essentially making the browser "sandbox" the document, never ever let it talk to anything external (http: or https:), be that resource loading or network (socket) requests.

More info here: https://content-security-policy.com/examples/meta/

I'll think of a better description for that option and close this issue once it's updated.

Thanks again!

**Comment by catfromplan9** [comment]
Excellent
