### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by mandreasik** [Y2Z/monolith#340]
Hi,

I want to inform you that on Ubuntu 22.04 and Ubuntu 22.04 (I've tested only these), the monolith binary from the release page fails due to missing shared libraries:
```
./monolith-gnu-linux-x86_64: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
Upon inspection using ldd, I found the following:
```
ldd ./monolith-gnu-linux-x86_64
	linux-vdso.so.1 (0x00007fff99fff000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc64650000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007efc6464b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc64646000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc63d17000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc6463f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc63b12000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efc64678000)
```
It appears that monolith was built using libssl 1.1, but Ubuntu ships with libssl 3:
```
||/ Name           Version          Architecture Description
+++-==============-================-============-====================================================
ii  openssl        3.0.8-1ubuntu1.2 amd64        Secure Sockets Layer toolkit - cryptographic utility
```

I understand that there are other ways, such as snap and cargo, to get monolith, but obtaining the binary is the fastest method.

Is there any chance of having the monolith binary built with libssl3 and released?

**Comment by hrvoj3e** [comment]
Fails on Manjaro (Arch) also with `openssl-3.2.0-1` installed on OS

**Comment by PnYMaT** [comment]
Same for me with debian bookworm

**Comment by snshn** [comment]
Uh-oh... the constant trouble with openssl, smh.  I swear I might just switch monolith to use the [openssl crate](https://crates.io/crates/openssl).  Sorry about it.  Will investigate it this week and try to solve it once and for all.

**Comment by codegod100** [comment]
one of my fav things about go is static binaries

**Comment by JokerQyou** [comment]
The linked PR was closed without merging, is `rustls` missing features?

**Comment by snshn** [comment]
It just didn't work with 99% of websites... I was so upset that it didn't.  I'm still trying to find a way that could rid monolith from the openssl dependency, but nothing seems to be working as well.  Maybe I did something wrong and rustls can be used, please feel free to resurrect that branch if you know how to make it work.
