### ISSUE TITLE
Monolith saves HTML with a NULL character in between every actual character

### ISSUE THREAD

**Issue by deanebarker** [Y2Z/monolith#352]
When Monolith saves an HTML file, for some reason, browsers auto-detect the encoding as UTF-16LE.

I couldn't figure out why, until I opened one of them in Visual Studio Code. It also auto-detected to UTF-16LE. When I forced it to UTF-8, which is what I saw:

![image](https://github.com/Y2Z/monolith/assets/1533433/dc745a7e-8185-4e7b-a8ac-43f9d3fd2b94)

There's seemingly a NULL character in between every other character?

This is how I called Monolith:

```
monolith -E utf-8 https://deanebarker.net/ > dbn-local.html
```

I'm at a loss here...

**Comment by yankov-pt** [comment]
@deanebarker  Which monolith version and OS  are you using?
Just tried with your command on a Fedora 39 machine and monolith 2.8.1.
I see that Windows defaults to UTF-16 internally, so maybe it's the OS assuming doing something funky when saving or the tool is picking up a default setting from OS? Haven't been through the code yet.

**Comment by deanebarker** [comment]
Monolith 2.8.1 on Windows 11

**Comment by snshn** [comment]
Hi Deane, thank you for raising the issue!
It's quite peculiar, even if it seems to be working fine when writing into a file without using pipes on Windows.  I'll look into it a bit more, it may be something that Monolith needs to account for when the output is STDOUT.
