### ISSUE TITLE
Outdated Project Reference in README

### ISSUE THREAD

**Issue by jpinnix** [Y2Z/monolith#364]
The `monk` project listed in the Related Projects section of the `monolith` README appears to be outdated, as it has not received updates for over 2 years and is not present in the cargo package registry. It may be beneficial to consider removing this reference to maintain the relevance and accuracy of the `monolith` documentation.

**Comment by AoJ** [comment]
I see that all references projects in README are outdated

**Comment by snshn** [comment]
Good point, no need to waste other people's time with links that won't help them.  If any of those projects become active again, I'll be sure to mention them in the file.  Thank you for letting me know!
