### ISSUE TITLE
How to get just HTML, no <script>

### ISSUE THREAD

**Issue by nikitavoloboev** [Y2Z/monolith#377]
Just ran `monolith --no-css --no-images "https://github.com/teamhanko/hanko/blob/main/frontend/elements/README.md#css-shadow-parts"`

And got back massive response

<img width="1538" alt="image" src="https://github.com/Y2Z/monolith/assets/6391776/3a661c4a-472a-4ef5-b1c6-0ea082eba39b">

Where 70% of response is that `<script>` tag. I just need to get HTML, not sure how.

Thanks. 🖤

**Comment by snshn** [comment]
Hello Nikita,

I think `--no-js` is what you're looking for, it should remove all `<script>` tags as well.  If the site very JS-heavy, try leveraging that Chrome-based pre-render trick described in the README, that should work.
