### ISSUE TITLE
What's the default location sites are being saved to?

### ISSUE THREAD

**Issue by TheMikeyRoss** [Y2Z/monolith#390]
I ran
```
monolith https://some-website.com
```

Without any flags or anytthing and it went through the process of downloading that site but I can't find the files. Is there a default location websites are being saved to?

**Comment by snshn** [comment]
Oh, this way it'd just print the HTML into the console as output.
Provide the "output" (`-o`) option when you run it to save the output into a file, e.g. `monolith https://some-website.com -o some.html`; and to see the location where it's saved, just run `pwd` after, and it'll tell you.

**Comment by TheMikeyRoss** [comment]
@snshn oh yes you're right, thanks 👍

**Comment by snshn** [comment]
You got it!
