### ISSUE TITLE
Saving all files separately like IDM.

### ISSUE THREAD

**Issue by pawan-poudel-github** [Y2Z/monolith#394]
Is there any way to save the files separately like what IDM does

**Comment by snshn** [comment]
I'm not sure I follow, sorry.  Are you talking about concurrent asynchronous network requests, automatically saving linked pages, or something else? 🤔

**Comment by pawan-poudel-github** [comment]
It provides a single html file and links all the stuffs there. Is there any way to download css, images, js etc separately and link them using link, script tag like same as source code?

Internet Download Manager (IDM) provides that but it's a paid one.

**Comment by snshn** [comment]
I think you can do that using Ctrl+S in any web browser.
