### ISSUE TITLE
Certain websites don't get retrieved at all

### ISSUE THREAD

**Issue by vflyson** [Y2Z/monolith#5]
- [x] https://cr.yp.to/djbdns/axfr-notes.html
 - [x] http://blog.checkpoint.com/2016/11/30/1-million-google-accounts-breached-gooligan/

**Comment by cbluth** [comment]
* [x] `https://cr.yp.to/djbdns/axfr-notes.html`

^^ this seems to work now.

**Comment by vflyson** [comment]
Oh, this was a bug report for the previous version/prottoype (in Node.js, from 2017).
I'm glad that Rust's `reqwest` library is a trooper and handles things that Node's libraries couldn't. Thanks for checking!

**Comment by vflyson** [comment]
Both of them now work. The second link just has a million assets, it takes like 30+ seconds to retrieve them all (since `monolith` right now is not async when it comes to retrieving assets). Closing the issue, thank you for the comment @cbluth
