### ISSUE TITLE
Support cookies.txt

### ISSUE THREAD

**Issue by aendra-rininsland** [Y2Z/monolith#55]
`wget` and `httrack` allow use of a file called cookies.txt to facilitate things like authentication -- this would be really useful for a variety of circumstances.

**Comment by vflyson** [comment]
This sounds like a good addition to #9 
Appears to be more secure in comparison to exposing session and login data via command line

**Comment by dorneanu** [comment]
+ 1

I think this is would be definitely a cool feature since I also want to save web pages that need me to login first (paywalls e.g.)
