### ISSUE TITLE
question:  does monolith save only the target webpage?

### ISSUE THREAD

**Issue by diehard88** [Y2Z/monolith#56]
All links found within the page will not be accessed, correct?

Thank you.

**Comment by vflyson** [comment]
Hello @diehard88
I can confirm that this program currently saves only the target web page. Any and all external links will be "fixed" to become full URLs (if they aren't) e.g. if there's `<a href="another-page.html">Go here</a>` on https://some-website.net/interesting-story.html, then monolith will save it as `<a href="https://some-website.net/another-page.html">Go here</a>`

**Comment by diehard88** [comment]
@vflyson "deep save" for the "deep web"?


:eyes:



:smile:
