### ISSUE TITLE
I really like monolith, so I made a thing

### ISSUE THREAD

**Issue by cbluth** [Y2Z/monolith#58]
I really like monolith,
and I really like ipfs,
so I made a thing that combines ipfs and monolith.
Its called PageSaver.
You can see it here: https://dweb.tools/pagesaver

Here is an example URL that you can share: https://dweb.tools/pagesaver?dag=QmVf8FqthAejRxmmRCLy9ydS77XVs5RHzHhmGzZZ9DM9ar

**Comment by cbluth** [comment]
@snshn 

i have uploaded the code, and added a feature, you can now enter youtube URLs (it doesnt use monolith for youtube).

**Comment by snshn** [comment]
This is very cool! I'd optimize it for mobile devices next as the icing on the cake. Thank you for helping save the Internet!

**Comment by cbluth** [comment]
@snshn i have updated the code again, now with fixed youtube support.
i will close this issue, thanks for monolith@!
