### ISSUE TITLE
doesn't seem to save images from CSS background url

### ISSUE THREAD

**Issue by officialkirill** [Y2Z/monolith#59]
Looks like monolith doesn't save images that are references by URL in CSS.

Otherwise, thanks, this tool is very useful!

**Comment by officialkirill** [comment]
alright, I'm no RUST programmer but I can see that monolith only loads CSS for embedding, but it should probably parse it too, if we want all the images loaded from CSS.

**Comment by snshn** [comment]
Greetings @officialkirill,

Thank you for the report! I'm currently working on parsing resources linked via style attributes and stylesheets, it should be finished and merged into the master branch in a couple of weeks.
