### ISSUE TITLE
Network requests need caching

### ISSUE THREAD

**Issue by snshn** [Y2Z/monolith#71]
It's redundant to request the same resource multiple times while saving the web page. Happens to be rather a rare occurrence with how today's websites include content, but it's still something that can happen (e.g. downloading the same resource for `<img />`). I believe the best place to implement it would be `http.rs`.

**Comment by voila** [comment]
Hello, I'd like to work on this.
What do you have in mind? 
I am thinking of using a `HashMap<String, String>` in `http.rs` to index `response.text()` by `response.url()`.

**Comment by snshn** [comment]
Hey there @voila!
Your help would be greatly appreciated on this one. Sounds like using hashmap is going to do the job. During its first prototype I used an object (it was initially written in JS), so I guess great minds think alike? Using strings for storing base64 sounds good to me. It could be cool to borrow dataURLs from that "store" to minimize the RAM footprint, but that perhaps should be a later enhancement. We could set it to cache only binary data, or, perhaps selecting what to cache and what not to cache by looking at the mime-type (e.g. always store base64 of png/svg/gif, never cache JS or CSS since it's unlikely those will ever get included more than once). 404's don't need to be cached I think, we just need to replace links to broken resources with full URLs.

If you could help implementing caching that would be of great help for everyone who uses monolith. We could always improve what and how it caches later, saving time on not making redundant requests is the most important part here.

**Comment by snshn** [comment]
Resolved by #75 thanks to @voila
