### ISSUE TITLE
error: linker `link.exe` not found

### ISSUE THREAD

**Issue by Oneideals** [Y2Z/monolith#79]
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option  

error: aborting due to previous error

error: could not compile `log`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option   

error: aborting due to previous error

error: could not compile `serde`.
warning: build failed, waiting for other jobs to finish...
error: could not compile `syn`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: could not compile `maybe-uninit`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option   

error: aborting due to previous error

error: could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found                                                                       
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option   

error: aborting due to previous error

error: could not compile `proc-macro2`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option   

error: aborting due to previous error

error: could not compile `byteorder`.
warning: build failed, waiting for other jobs to finish...
error: linker `link.exe` not found
  |
  = note: 系统找不到指定的文件。 (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option   

error: aborting due to previous error

error: failed to compile `monolith v2.0.23 (C:\Users\cheng\monolith)`, intermediate artifacts can be found at `C:\Users\cheng\monolith\target`

Caused by:
  could not compile `winapi`.

To learn more, run the command again with --verbose.

**Comment by snshn** [comment]
Hi @Oneideals 

I believe this may be exactly the same problem as previously mentioned in #38

**Comment by snshn** [comment]
As of today you can grab `monolith.exe` from the Releases page, there's a pipeline in place to build and attach the latest executable to every new release.
