### ISSUE TITLE
Doesn't save images for google.com

### ISSUE THREAD

**Issue by rajdeepbharati** [Y2Z/monolith#90]
Run this:
```
monolith https://www.google.com > googl.html
```
This is how my downloaded page looks like (it doesn't have images and some other assets).
![Screenshot 2019-12-23 at 2 46 39 PM](https://user-images.githubusercontent.com/30660439/71348683-13c02080-2593-11ea-8110-b04e0d075824.png)

**Comment by snshn** [comment]
Hi there,

it's been fixed in the latest release (2.1.0).
It seems like the version available on brew is still 2.0.16. I'll work on updating it there.

Thank you for the report!

**Comment by rajdeepbharati** [comment]
Thanks

**Comment by snshn** [comment]
if you do `brew upgrade monolith` you should get 2.1.0 on your machine now, that'll let background images to be properly embedded
